# Generated by Django 5.2.7 on 2025-10-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(help_text='Enter the brand of the vehicle (e.g., Toyota, Honda)', max_length=100, verbose_name='Brand Name')),
                ('vehicle_name', models.CharField(help_text='Enter the vehicle model name (e.g., Corolla, Civic)', max_length=100, verbose_name='Vehicle Name')),
                ('model_number', models.CharField(help_text='Enter the model or series number', max_length=50, verbose_name='Model Number')),
                ('registration_number', models.CharField(help_text='Unique registration number of the vehicle', max_length=50, unique=True, verbose_name='Registration Number')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck'), ('bus', 'Bus'), ('van', 'Van'), ('other', 'Other')], max_length=20, verbose_name='Vehicle Type')),
                ('vehicle_subtype', models.CharField(blank=True, help_text='Enter subtype such as Sedan, SUV, or Hatchback', max_length=50, null=True, verbose_name='Vehicle Subtype')),
                ('variant', models.CharField(choices=[('base', 'Base'), ('standard', 'Standard'), ('deluxe', 'Deluxe'), ('sport', 'Sport'), ('luxury', 'Luxury'), ('limited', 'Limited Edition'), ('premium', 'Premium'), ('custom', 'Custom')], help_text='Select the variant or trim level of the vehicle', max_length=30, verbose_name='Variant')),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi_automatic', 'Semi-Automatic')], max_length=20, verbose_name='Transmission Type')),
                ('chassis_number', models.CharField(max_length=100, unique=True, verbose_name='Chassis Number')),
                ('engine_number', models.CharField(max_length=100, unique=True, verbose_name='Engine Number')),
                ('description', models.TextField(blank=True, help_text='Optional: provide details about the vehicle', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
